#!/usr/bin/env python3
"""
Create a single consolidated JSON file with all names and commentaries
"""

import json
import os
from pathlib import Path

# Base paths
base_dir = Path(__file__).parent.parent
naamavali_dir = base_dir / 'Naamavali'
soubhagya_dir = base_dir / 'SoubhagyaBhaskara'
datta_dir = base_dir / 'DattaCommentary'

all_names = []

for i in range(1, 1001):
    padded = str(i).zfill(4)

    entry = {
        'number': i,
        'name': '',
        'soubhagya_commentary': '',
        'datta_commentary': {
            'name_transliterated': '',
            'meaning': '',
            'commentary': ''
        }
    }

    # Read Naamavali name (Devanagari)
    naamavali_file = naamavali_dir / f'{padded}.txt'
    if naamavali_file.exists():
        with open(naamavali_file, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            entry['name'] = content

    # Read SoubhagyaBhaskara commentary
    soubhagya_file = soubhagya_dir / f'{padded}.md'
    if soubhagya_file.exists():
        with open(soubhagya_file, 'r', encoding='utf-8') as f:
            content = f.read()
            # Remove frontmatter if present
            if content.startswith('---'):
                parts = content.split('---', 2)
                if len(parts) >= 3:
                    content = parts[2].strip()
            entry['soubhagya_commentary'] = content

    # Read DattaPeeta commentary
    datta_file = datta_dir / f'{padded}.json'
    if datta_file.exists():
        with open(datta_file, 'r', encoding='utf-8') as f:
            datta_data = json.load(f)
            entry['datta_commentary'] = {
                'name_transliterated': datta_data.get('name_transliterated', ''),
                'meaning': datta_data.get('meaning', ''),
                'commentary': datta_data.get('commentary', '')
            }

    all_names.append(entry)

# Write consolidated JSON with header
output_file = base_dir / 'Code' / 'all-names.json'

# Create the data structure with a warning header
output_data = {
    "_comment": "DO NOT EDIT THIS FILE MANUALLY - Generated automatically by create_consolidated_json.py",
    "_generated_at": "Auto-generated from Naamavali, SoubhagyaBhaskara, and DattaCommentary folders",
    "names": all_names
}

with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(output_data, f, ensure_ascii=False, indent=2)

print(f"Created consolidated JSON with {len(all_names)} names at {output_file}")
